### ISSUE TITLE
Admin Interface crashes

### ISSUE THREAD

**Issue by thomas-SGB** [civicrm/org.civicrm.contactlayout#75]
Dear Coleman,

thank you so much for the lovely Contact Layout Editor. Since updating from 1.6 to 1.7 I cannot access the backend to edit the contact summarys. Have you any idea what could have happened?

Kind regards
Thomas

![Screenshot_2020-08-18 CiviCRM Schweizerischer Gewerkschaftsbund](https://user-images.githubusercontent.com/54853415/90501700-04f33300-e14d-11ea-9aa4-80f3e05a138c.png)

**Comment by colemanw** [comment]
Please clear your caches and try again. If it still fails, please open up your browser console (F12) and include those error messages with your screenshot.

**Comment by aardgoose** [comment]
I see the same error (CiviCRRM 5.28.2)


Console output (hostname removed)

angular.js:14199 TypeError: Cannot read property 'reloadModels' of undefined
    at new <anonymous> (https://.../wp-content/uploads/civicrm/persist/contribute/dyn/angular-modules.ba288289ee19f1b9b7c916e2501a63e2.js:537:16)
    at Object.instantiate (https://.../wp-content/plugins/civicrm/civicrm/bower_components/angular/angular.min.js?r=da51i:42:109)
    at https://.../wp-content/plugins/civicrm/civicrm/bower_components/angular/angular.min.js?r=da51i:91:374
    at Object.link (https://.../wp-content/uploads/civicrm/persist/contribute/dyn/angular-modules.ba288289ee19f1b9b7c916e2501a63e2.js:2219:274)
    at https://.../wp-content/plugins/civicrm/civicrm/bower_components/angular/angular.min.js?r=da51i:16:71
    at sa (https://.../wp-content/plugins/civicrm/civicrm/bower_components/angular/angular.min.js?r=da51i:82:244)
    at n (https://.../wp-content/plugins/civicrm/civicrm/bower_components/angular/angular.min.js?r=da51i:68:6)
    at g (https://.../wp-content/plugins/civicrm/civicrm/bower_components/angular/angular.min.js?r=da51i:59:428)
    at https://.../wp-content/plugins/civicrm/civicrm/bower_components/angular/angular.min.js?r=da51i:59:67
    at https://.../wp-content/plugins/civicrm/civicrm/bower_components/angular/angular.min.js?r=da51i:64:67 <div ng-view="" class="ng-scope">
(anonymous) @ angular.js:14199

**Comment by colemanw** [comment]
Could you please try the patch in #76 and see if it fixes your problem?

**Comment by aardgoose** [comment]
That appears to work, admin screen loads and functions correctly.
Thanks for the fast response.
