### ISSUE TITLE
network error when saving block based on profile

### ISSUE THREAD

**Issue by jmcclelland** [civicrm/org.civicrm.contactlayout#77]
When I add a block based on a profile, and I click the block directly to display an AJAX edit form, and the profile includes a CheckBox field, I get a network error when I hit save.

Inspector reveals:
```
CiviCRM_API3_Exception: "'1' is not a valid option for field custom_1"

#0 /var/www/powerbase/sites/all/extensions/contactlayout/CRM/Contactlayout/Form/Inline/ProfileBlock.php(123): civicrm_api3("Profile", "submit", (Array:22))
#1 /var/www/powerbase/sites/all/modules/civicrm/CRM/Core/Form.php(484): CRM_Contactlayout_Form_Inline_ProfileBlock->postProcess()
#2 /var/www/powerbase/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Upload.php(153): CRM_Core_Form->mainProcess()
#3 /var/www/powerbase/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Upload.php(120): CRM_Core_QuickForm_Action_Upload->realPerform(Object(CRM_Contactlayout_Form_Inline_ProfileBlock), "upload")
#4 /var/www/powerbase/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Upload->perform(Object(CRM_Contactlayout_Form_Inline_ProfileBlock), "upload")
#5 /var/www/powerbase/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Contactlayout_Form_Inline_ProfileBlock), "upload")
#6 /var/www/powerbase/sites/all/modules/civicrm/CRM/Core/Controller.php(335): HTML_QuickForm_Page->handle("upload")
#7 /var/www/powerbase/sites/all/modules/civicrm/CRM/Utils/Wrapper.php(98): CRM_Core_Controller->run()
#8 /var/www/powerbase/sites/all/modules/civicrm/CRM/Core/Page/AJAX.php(65): CRM_Utils_Wrapper->run("CRM_Contactlayout_Form_Inline_ProfileBlock")
#9 /var/www/powerbase/sites/all/modules/civicrm/CRM/Core/Invoke.php(278): CRM_Core_Page_AJAX::run()
#10 /var/www/powerbase/sites/all/modules/civicrm/CRM/Core/Invoke.php(68): CRM_Core_Invoke::runItem((Array:12))
#11 /var/www/powerbase/sites/all/modules/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke((Array:3))
#12 /var/www/powerbase/sites/all/modules/civicrm/drupal/civicrm.module(454): CRM_Core_Invoke::invoke((Array:3))
#13 /var/www/powerbase/includes/menu.inc(527): civicrm_invoke("ajax", "inline")
#14 /var/www/powerbase/index.php(21): menu_execute_active_handler()
#15 {main}

```

ContactEditor seems to be feeding CiviCRM the checkbox values in the wrong format. This may be related to https://github.com/civicrm/civicrm-core/pull/17562.

**Comment by colemanw** [comment]
Can you please try out this fix: #80

**Comment by colemanw** [comment]
Ping @jmcclelland ^

**Comment by jmcclelland** [comment]
Sorry for the slow response. I just tested and it works! Thanks for the fix.

**Comment by colemanw** [comment]
Cool thanks for testing @jmcclelland
